version: "3"
services:
  aspnet:
    build:
      context: .
    ports:
      - "80:80"
    network:
      - minitwit
    restart: always
    deploy: 
      replicas: 3
      update_config:
        parallelism: 1
        delay: 20s

networks:
  minitwit:
    driver: overlay

